name: 01-building-blocks

on: push

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Building the project..."

  hello2:
    runs-on: ubuntu-latest
    steps:
      - name: say hello2
        run: echo "next is building..."
